spring.datasource.url=jdbc:mysql://localhost:3306/textile_inventory?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=9791990962

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080
